server:
  port: ${AUTH_SERVICE_PORT:8083}

spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  movie:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect