server:
  port: ${CATALOG_SERVICE_PORT:8081}

spring:
  application:
    name: catalog-service

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: ${CATALOG_DB_URL}
    username: ${CATALOG_DB_USERNAME}
    password: ${CATALOG_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  gateway-secret: ${GATEWAY_SECRET}
  internal-secret: ${INTERNAL_SECRET}