server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://host.docker.internal:8083}
          predicates:
            - Path=/api/v1/auth/**

        - id: catalog-service-public-movies
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/movies/**,/api/v1/catalog/cinemas/**,/api/v1/catalog/showtimes/**
            - Method=GET

        - id: catalog-service-protected
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://host.docker.internal:8082}
          predicates:
            - Path=/api/v1/booking/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://host.docker.internal:8084}
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter

  movie:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}

app:
  gateway-secret: ${GATEWAY_SECRET}