server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://host.docker.internal:8083}
          predicates:
            - Path=/api/v1/auth/**

        - id: catalog-service-public-get
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/movies/**,/api/v1/catalog/cinemas/**,/api/v1/catalog/showtimes/**,/api/v1/catalog/reviews/**
            - Method=GET

        - id: catalog-service-protected-get
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/rooms/**,/api/v1/catalog/snacks/**
            - Method=GET
          filters:
            - AuthenticationFilter

        - id: catalog-service-protected-write
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/**
            - Method=POST,PUT,PATCH,DELETE
          filters:
            - AuthenticationFilter

        - id: catalog-service-user-protected
          uri: ${CATALOG_SERVICE_URL:http://host.docker.internal:8081}
          predicates:
            - Path=/api/v1/catalog/**
            - Method=POST,PUT,PATCH,DELETE
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://host.docker.internal:8082}
          predicates:
            - Path=/api/v1/booking/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://host.docker.internal:8084}
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter

  movie:
    jwt:
      secret: ${JWT_SECRET:VmVyeVNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uU3ByaW5nQm9vdEFwcGxpY2F0aW9u}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}

app:
  gateway-secret: ${GATEWAY_SECRET:a3f8c9e1d2b5f6a0b9d8e4f7c3a2b1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b7a2}