server:
  port: ${BOOKING_SERVICE_PORT:8082}

spring:
  application:
    name: booking-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2
          max-interval: 10000

  datasource:
    url: ${BOOKING_DB_URL}
    username: ${BOOKING_DB_USERNAME}
    password: ${BOOKING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  gateway-secret: ${GATEWAY_SECRET:a3f8c9e1d2b5f6a0b9d8e4f7c3a2b1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b7a2}
  internal-secret: ${INTERNAL_SECRET:8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c}
  catalog-service-url: ${CATALOG_SERVICE_URL:http://localhost:8081/api/v1/catalog}
  payment-service-url: ${PAYMENT_SERVICE_URL:http://localhost:8084/api/v1/payment}
  notification-service-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
  reminder:
    before-minutes: ${SHOWTIME_REMINDER_BEFORE_MINUTES:60}
  rabbitmq:
    exchange: movie.ticket.exchange
    booking-confirm-request-queue: booking.confirm.request.queue
    booking-confirm-request-routing-key: booking.confirm.request
    booking-confirm-result-queue: payment.booking.confirm.result.queue
    booking-confirm-result-routing-key: payment.booking.confirm.result
  rest-client:
    connect-timeout-ms: ${REST_CLIENT_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${REST_CLIENT_READ_TIMEOUT_MS:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      internal:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: false
  retry:
    instances:
      internal:
        max-attempts: 3
        wait-duration: 500ms
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
